[package]
name = "sunbeam_html"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
log = "0.4.26"
sunbeam_macros = { path = "crates/sunbeam_macros" }
pollster = "0.4.0"
