[package]
name = "sunbeam_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["extra-traits", "visit"] }
